/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardTutorialRouteImport } from './routes/_dashboard/tutorial'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard/home'
import { Route as DashboardHistoryRouteImport } from './routes/_dashboard/history'
import { Route as DashboardPlayIndexRouteImport } from './routes/_dashboard/play/index'
import { Route as DashboardPlayGameIdRouteImport } from './routes/_dashboard/play/$gameId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTutorialRoute = DashboardTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlayIndexRoute = DashboardPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlayGameIdRoute = DashboardPlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof DashboardHistoryRoute
  '/home': typeof DashboardHomeRoute
  '/tutorial': typeof DashboardTutorialRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/play/$gameId': typeof DashboardPlayGameIdRoute
  '/play': typeof DashboardPlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof DashboardHistoryRoute
  '/home': typeof DashboardHomeRoute
  '/tutorial': typeof DashboardTutorialRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/play/$gameId': typeof DashboardPlayGameIdRoute
  '/play': typeof DashboardPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/history': typeof DashboardHistoryRoute
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_dashboard/tutorial': typeof DashboardTutorialRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_dashboard/play/$gameId': typeof DashboardPlayGameIdRoute
  '/_dashboard/play/': typeof DashboardPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/home'
    | '/tutorial'
    | '/auth/login'
    | '/auth/signup'
    | '/play/$gameId'
    | '/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/home'
    | '/tutorial'
    | '/auth/login'
    | '/auth/signup'
    | '/play/$gameId'
    | '/play'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/history'
    | '/_dashboard/home'
    | '/_dashboard/tutorial'
    | '/auth/login'
    | '/auth/signup'
    | '/_dashboard/play/$gameId'
    | '/_dashboard/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/tutorial': {
      id: '/_dashboard/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof DashboardTutorialRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/history': {
      id: '/_dashboard/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/play/': {
      id: '/_dashboard/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof DashboardPlayIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/play/$gameId': {
      id: '/_dashboard/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof DashboardPlayGameIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardTutorialRoute: typeof DashboardTutorialRoute
  DashboardPlayGameIdRoute: typeof DashboardPlayGameIdRoute
  DashboardPlayIndexRoute: typeof DashboardPlayIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardTutorialRoute: DashboardTutorialRoute,
  DashboardPlayGameIdRoute: DashboardPlayGameIdRoute,
  DashboardPlayIndexRoute: DashboardPlayIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
